### ISSUE TITLE
EAMapReader v4.13 & CARTO v7.1 - ValueError: could not convert string to float: '' when Reading map.mesh

### ISSUE THREAD

**Issue by Jsalas424** [stephan1312/SlicerEAMapReader#11]
Hello,

I am importing a zip file and ran into the following error:

```
Importing CARTO 3 map:
Extracting archive /.../Export_EVI-34-01_02_2030-12-08-45.zip to /private/var/folders/gk/xk6mdq_d7m7db3_6d4_6sg5w0000gn/T/Slicer-jon/EAMapReader/20220728_133545_786
Reading 2-1-1-1-ReLVFAM_VT.mesh:

Traceback (most recent call last):
  File "/Applications/Slicer.app/Contents/EAMapReader-Slicer-4.13/lib/Slicer-4.13/qt-scripted-modules/EAMapReader.py", line 129, in onButtonCarto
    if not self.logic.readCarto(self.filename):
  File "/Applications/Slicer.app/Contents/EAMapReader-Slicer-4.13/lib/Slicer-4.13/qt-scripted-modules/EAMapReader.py", line 493, in readCarto
    if not self.readCartoMesh(os.path.join(tempDir, filename)):
  File "/Applications/Slicer.app/Contents/EAMapReader-Slicer-4.13/lib/Slicer-4.13/qt-scripted-modules/EAMapReader.py", line 579, in readCartoMesh
    verticesLong = self.TextToFloat(verticesText)
  File "/Applications/Slicer.app/Contents/EAMapReader-Slicer-4.13/lib/Slicer-4.13/qt-scripted-modules/EAMapReader.py", line 336, in TextToFloat
    thisNumbers.append(float(lineSplit[j])) 
ValueError: could not convert string to float: ''
```

I can provide the zip file in question if that will help. 

Slicer v5.0.3
EAMapReader v4.13
CARTO v7.1

**Comment by Jsalas424** [comment]
I installed [Slicer v4.11 ](https://slicer-packages.kitware.com/#collection/5f4474d0e1d8c75dfc70547e/folder/60ac0ce2ae4540bf6a899ecc)and the corresponding [EAMapReader version](https://github.com/stephan1312/SlicerEAMapReader/blob/master/EAMapReader-Slicer-4.11.zip) - This was not an issue using the same CARTO zip.

**Comment by stephan1312** [comment]
Obviously, there have been some changes how Python interprets certain regular expressions (specifically the re.split() function which splits strings along RegEx-defined separators). I have debugged the extension and will upload a version for Slicer 5.0.x shortly.
